### ISSUE TITLE
TypeError: Object has no method 'module'

### ISSUE THREAD

**Issue by annie** [ColumbiaJS/js-course#35]
My DI.js is set up exactly as outlined in the hw README:

```
module.exports = {
    modules: {},
    module: function (name, dependencies) {
        // the function
    }
};
```

But for some reason I keep getting a "TypeError: Object #<Object> has no method 'module'" and "ReferenceError: modules is not defined".  Am I missing something?

**Comment by emmalovato** [comment]
not sure if you're still getting this error, but maybe you're just missing a return statement in the constructor?

**Comment by annie** [comment]
@emmalovato Still getting the error, and I do have a return statement.  And even if I didn't, shouldn't gulp still see that I have modules and module defined in the module.exports object??

**Comment by levbrie** [comment]
@azhang496 Can you include the full stack trace so I can see where this error is coming from?

**Comment by annie** [comment]
@levbrie 

```
  1) Inject dependencies "before all" hook:
     ReferenceError: modules is not defined
      at Object.module.exports.module (/Users/Annie/Documents/javascript/w3101hws/hw3/lib/di-simple/DI.js:38:7)
      at Context.<anonymous> (/Users/Annie/Documents/javascript/w3101hws/hw3/lib/di-simple/DI.spec.js:15:16)
      at callFn (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:251:21)
      at Hook.Runnable.run (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:259:10)
      at Object._onImmediate (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)

  2) Inject dependencies "before all" hook:
     TypeError: Object #<Object> has no method 'module'
      at Context.<anonymous> (/Users/Annie/Documents/javascript/w3101hws/hw3/lib/di/DI.spec.js:115:16)
      at callFn (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:251:21)
      at Hook.Runnable.run (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:259:10)
      at Object._onImmediate (/Users/Annie/Documents/javascript/w3101hws/hw3/node_modules/gulp-mocha/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by levbrie** [comment]
@azhang496 2 things here:
1. You have the right idea here, but when you set up your DI.js exports:

``` js
module.exports = {
  modules: {},
  module: function(name, dependencies) {
   // your function here
  }
};
```

The only way to reference the modules object from inside of the module function is with a this reference, as in: `this.modules[name]`.
1. When the module function is called and a new module is created, you need to make sure that you return an object and not a function:

``` js
module: function (name, dependencies) {
  // some code checking if you have dependencies passed in and want to create a module or get one
  // if creating:
  var newModule = {
    name: name,
    deps: deps,
    register: register,
    // etc.
  };
  return newModule;
  // your module functions, etc.
}
```

Does that make sense?

**Comment by annie** [comment]
@levbrie The first one makes sense.  But for #2, my current code looks almost exactly like your example but I'm still getting the TypeError!

**Comment by levbrie** [comment]
@azhang496 The second error that you're getting is coming from: lib/di/DI.spec.js:115:16, which is in the lib/di/ directory and not the lib/di-simple directory.  As of right now, at least in your repo on Github, you have only implemented that functionality in di-simple, so once you're finished with di-simple/DI.js and you copy that code over to di/DI.js, that error should go away.  Let me know if that works!

Best, 
Lev

**Comment by annie** [comment]
@levbrie Oh wow yeah it was just that.  I thought using describe.only was taking care of that.  Thank you so much!!

**Comment by levbrie** [comment]
Absolutely!
